import "../globals.css";

export const metadata = {
  title: "Next.js Starter",
  description: "Generated by create next app",
  ogTitle: "Next.js Starter",
  ogDescription: "Generated by create next app",
  ogImage: 'https://tracker-w-gb16702.vercel.app/images/bgC.jpg',
};

export default function RootLayout({ children }) {
  return <>{children}</>;
}
