import "../globals.css";

import Header from "../components/common/Partials/Header/Header";
import Footer from "../components/common/Partials/Footer/Footer";
import { decodeSession } from "../../lib/decodeSession";
import Nav from "../components/common/Partials/Header/Navigation/Nav";

export const metadata = {
  title: "Next.js Starter",
  description: "Generated by create next app",
  ogTitle: "Next.js Starter",
  ogDescription: "Generated by create next app",
  // ogImage: '/images/og-image.jpg',
};

export default async function ClientLayout({ children }) {
  const session = await decodeSession();

  return (
    <>
      <Header>
        <Nav session={session} />
      </Header>
      <main className="w-[100%] h-[100%]">{children}</main>
      <Footer />
    </>
  );
}
