import GameSectionHeader from "../components/common/Partials/Header/GameSectionHeader";
import "../globals.css";

export const metadata = {
  title: "Next.js Starter",
  description: "Generated by create next app",
  ogTitle: "Next.js Starter",
  ogDescription: "Generated by create next app",
};

export default async function GameLayout({ children }) {
  const response = await fetch("http://localhost:8000/api/games", {
    cache: "no-store",
  });

  const { games } = await response.json();

  const headerObject = games.map((g_) => ({
    name: g_.name,
    slug: g_.slug,
  }));

  return (
    <>
      <GameSectionHeader obj={headerObject} />
      {children}
    </>
  );
}
