import './globals.css'
import {poppins} from './fonts'
import AuthProvider from './components/common/Global/AuthProvider'

export const metadata = {
  title: 'Next.js Starter',
  description: 'Generated by create next app',
  ogTitle: 'Next.js Starter',
  ogDescription: 'Generated by create next app',
  // ogImage: '/images/og-image.jpg',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={poppins.className}>
      <body className='bg-[#1E1E20]'>
      <AuthProvider>
        {children}
      </AuthProvider>
      </body>
    </html>
  )
}
