import "../globals.css";

export const metadata = {
  title: "Next.js Starter",
  description: "Generated by create next app",
  ogTitle: "Next.js Starter",
  ogDescription: "Generated by create next app",
  // ogImage: '/images/og-image.jpg',
};

export default function RootLayout({ children }) {
  return (
    <>
      <main className="w-[100] h-[100vh] bg-white">{children}</main>
    </>
  );
}
